### ISSUE TITLE
Make this bundle compatible with Symfony3

### ISSUE THREAD

**Issue by quentin-st** [jeroendesloovere/vcard-bundle#1]
Currently, this bundle cannot be installed on a Symfony 3.0 project:

```
Problem 1
  - jeroendesloovere/vcard-bundle 1.0.0 requires jeroendesloovere/vcard dev-master -> no matching package found.
  - Conclusion: remove symfony/symfony v3.0.0
```

Seems like a rash conclusion for me!

Would it be possible to update this bundle for it be installable on a Symfony 3.0 project?

**Comment by jeroendesloovere** [comment]
Hi @chteuchteu,

Haha, indeed that is a bit hard :-P.
I will investigate this for you.

**Comment by quentin-st** [comment]
Hi! I checked by forking your repo and updating to Symfony3 this afternoon: everything seems to work fine!

**Comment by jeroendesloovere** [comment]
Did you tried the following

``` bash
composer require jeroendesloovere/vcard
```

that works for me.

**Comment by quentin-st** [comment]
Don't we need the vcard-bundle alongside with vcard? If not, what's the purpose of vcard-bundle?

**Comment by jeroendesloovere** [comment]
Hi @chteuchteu 
I just released a [new version 1.2.0](https://github.com/jeroendesloovere/vcard-bundle/releases/tag/1.2.0) which works on symfony 3.

**Comment by quentin-st** [comment]
Hi @jeroendesloovere ! Thank you for this release! I just tried with my project and unfortunately, it doesn't work: composer yells the same error I posted earlier.

I'm using this line in my `composer.json` file: `"jeroendesloovere/vcard-bundle": "~1.2.0"`

I think that this line makes it fail:

```
"symfony/framework-bundle": "~2.3"
```

Couldn't we use `>2.3` as version number?

**Comment by jeroendesloovere** [comment]
Hi @chteuchteu, indeed, in "dev" enviroment an old "symfony/framework-bundle" gets loaded.
Can you try the [new release 1.2.1](https://github.com/jeroendesloovere/vcard-bundle/releases/tag/1.2.1), does it work?

**Comment by quentin-st** [comment]
v1.2.1 works fine, thank you!
